export { default as HomePage } from './Homepage'
export { default as Collection } from './Collection'
export { default as ProductDetail } from './ProductDetail'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Checkout } from './Checkout'